-state main
look_creature
recall
if Zoltan
set_state_cont testsay

-state testsay
listen
recall
if password
set_state_cont heard_password

-state heard_password
say you know the password, and may pass
move north
set_state main

-state prep
forget_all
remember
set_state one

-state one
move_toward

-state done
look_creature
recall
if boar
set_state boar
say "State Done"

-state boar
move_toward
if DONE
set_state boar_done

-state boar_done
say "boar done"
